Global:
  infer_imgs: "./images/wangzai.jpg"
  # rec_inference_model_dir: "./models/product_ResNet50_vd_aliproduct_v1.0_infer"
  rec_inference_model_dir: "./models/general_PPLCNet_x2_5_lite_v1.0_infer"
  batch_size: 1
  use_gpu: False
  enable_mkldnn: False
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False


# 数据预处理
RecPreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

# 数据后处理
RecPostProcess: null

# vec search config
IndexProcess:
  index_method: "HNSW32" # supported: HNSW32, IVF, Flat
  image_root: "./drink_dataset_v1.0/gallery/"
  index_dir: "./drink_dataset_v1.0/index_all"
  data_file:  "./drink_dataset_v1.0/gallery/drink_label_all.txt"
  index_operation: "new" # suported: "append", "remove", "new"
  delimiter: "\t"
  dist_type: "IP"
  embedding_size: 512
  batch_size: 32
  return_k: 5
  score_thres: 0.5